### ISSUE TITLE
extend char limits of danganronpa

### ISSUE THREAD

**Issue by marcussacana** [doggydogworld/project-zetsubou-hacks#1]
i like if you post a txt with info to up the char limit of danganronpa 2 of psp.. can you make one?

**Comment by doggydogworld** [comment]
The extend hack for 2 was pretty far from completion when NISA announced their 2 localization and we stopped work. They actually reduced the buffer limit from 54 in 1 to 28 in 2 which made things a lot more complicated. Good luck

**Comment by marcussacana** [comment]
^^ i make my own patch here []http://i.imgur.com/O2Umx1c.png[]
